import React from 'react'
// this compenent is called to the aboutAstrology.js page and displays the legends assosciated with each astrology sign
const AboutAstrologyLegends = (props) => {
    return (
        <>
            {!props.sign ? <div>
                <h1 className="astroTitle mt-5">The Legend Behind Each Sign</h1>
                <p className="aboutAstrologyDesc">In ancient times, the sky above us was seen as a giant hollow dome rising over a flat earth, much like an inverted teacup resting on a saucer. Later, this vision of the Earth and the surrounding sky changed to that of a hollow sphere - like an enormous soap bubble with the globe of the Earth in its center. The Sun made a journey every year around the edge of the sky-bubble; within the space of one year it made a complete circle.</p>
                <p className="aboutAstrologyDesc">The path of the Sun's circle around the Earth is known as the ecliptic. This narrow band of the Sun's path is the zodiac. The zodiac is a belt circling the earth, 16 degrees wide (8 degrees above the ecliptic and 8 degrees below the ecliptic) and 360 degrees around. Within this belt are contained the orbits of all the planets in our solar system except Pluto, which has an extraordinarily wide path. Also within this belt are stars, which the ancients arranged in patterns called constellations. To the early stargazers most of these constellations looked like animals, so this belt of constellations became known as the zodiac - from the Greek word zodiakos, meaning, 'circle of animals.'</p>
                <p className="aboutAstrologyDesc">The zodiac is divided into twelve constellations, each with a name and each given the shape of an animal or figure. Using these constellations, the ancient astrologers named the twelve astrological signs.</p>
                <p className="aboutAstrologyDesc">The zodiac belt may be imagined (in the sense that it is a man-made division of the heavens), but the stars within that belt are real. If you could simultaneously stand at various spots circling our globe, you would be able to see all twelve constellations in the skyat one time. Those constellations were known long before Ptolemy categorized them in his textbooks, and each constellation has a story handed down through ancient myths. This folklore has become very much a part of our knowledge if each astrological sign.</p>
            </div> : props.sign === "Aries" ? <div>
                <h1 className="astroTitle mt-5">Aries, the Ram</h1>
                <p className="legendPara">The first sign of the zodiac is represented by the Ram. In mythology, The Ram has always been courageous and enterprising, a lively, energetic animal able to bound over obstacles and rocky terrain.</p>
                <p className="legendPara">The story of the Ram begins in ancient Greece with a king named Athamus who ruled the province of Boetia. Athamus married a woman called Nephele, and they had two beautiful children, a son and daughter they named Phrixus and Helle.</p>
                <p className="legendPara">After a time, Athamus grew tired of Nephele and deserted her. He took a second wife, Ino, and they had two sons. Ino was a jealous and conniving woman who hated her stepchildren Phrixus and Helle, and set about plotting their deaths.</p>
                <p className="legendPara">The first thing she did was convince the women of her country to roast the corn before planting it. This effectively cancelled out the crops that year. Famine swept the land. The kind sent a messenger to the Oracle at Delphi to find out what caused the crop failure. Apparently, it never occurred to him to ask the women who planted the crops, but this is the sort of oversight of which some modern political leaders are also guilty.</p>
                <p className="legendPara">Ino managed to bribe the king's messenger to return from Delphi and tell the king that the crops would not grow again until the lives of his children Phrixus and Helle were sacrificed to the god Jupiter. The gullible king planned to have his son and daughter killed in order to save his people.</p>
                <p className="legendPara">A quick shift now to Phrixus and Helle, who were tending their sheep. In their flock was a Ram with golden fleece. This Golden Ram had been given to their mother Nephele as a present from the god Hermes (Mercury). Nephele, getting wind of what evil was afoot, begged the Ram to save her children. The Ram spoke with the voice of a man to warn Phrixus and Helle of their danger, then told them to climb onto his back. Then he flew with them across the sea.</p>
                <p className="legendPara">Unfortunately, as they were crossing the strait that divides Europe and Asia, Helle grew dizzy and faint and slipped off the Ram's back. She fell into the sea and drowned. To this day, the strait into which she fell is named after her, the Hellespont.</p>
                <p className="legendPara">Her brother Phrixus, however, was carried safely to the land of Colchis. This put an end to the plot of the villianous Ino, though it does not seem to have done much to relieve the famine or to have brought King Athamus to his senses.</p>
                <p className="legendPara">Rather ungratefully it would seem, Phrixus killed the Golden Ram as a sacrifice to Jupiter, who in turn placed the Ram's likeness among the stars in heaven to honor him for his heroism.</p>
            </div>
                    : props.sign === 'Taurus' ? <div>
                        <h1 className="astroTitle mt-5">Taurus, the Bull</h1>
                        <p className="legendPara">The second sign of the zodiac is represented by the Bull, an animal that is both fierce and gentle and has always symbolized strength and sexuality.</p>
                        <p className="legendPara">The myth of the Bull begins with Jupiter, supreme god of ancient Greece, ruler of heaven, of lesser gods, and men. Jupiter had a strong romantic streak, and had numerous love affairs, wives, and mistresses. One such love affair concerns the beautiful Princess Europa, daughter of the King of Phoenicia.</p>
                        <p className="legendPara">Europa led a very sheltered existence in her father's palace and knew nothing of the world outside. One night she had a prophetic dream in which a strange woman held out her arms to Europa and said, 'I shall bring you to Jupiter, for destiny has appointed you his beloved.'</p>
                        <p className="legendPara">Sure enough, that day when Europa and a group of young maidens went out to pick roses and hyacinths in a meadow by the sea, Jupiter saw her and was thunderstruck by her beauty. There and then he determined to have her.</p>
                        <p className="legendPara">Jupiter knew that an innocent young girl like Europa would run from him if he showed himself in his own godlike image, so he transformed himself into a Bull. He became not an ordinary bull, but a magnificent white Bull with jewel-like horns and a silver crescent moon in the middle of his fore-head.</p>
                        <p className="legendPara">Europa was fascinated by the beautiful, gentle Bull, and began to caress him. Finally she climbed onto his back. That was just what Jupiter wanted. He sprang into the air and carried her away to the island of Crete. There, he changed himself back to his true likeness and declared his love for Europa. Under the boughs of a large tree, he and Europa became lovers.</p>
                        <p className="legendPara">Not long afterward Venus, the goddess of love, appeared to Europa to confess that she was the strange women in the dream. From now on, Venus told her, the continent to which Jupiter had taken her would be know as Europe.</p>
                        <p className="legendPara">This adulterous love story (Jupiter was married the goddess Juno) has a happy ending. Europa bore Jupiter three children, and Jupiter took the likeness of the Bull and placed it in the heavens.</p>
                    </div> : props.sign === 'Gemini' ? <div>
                        <h1 className="astroTitle mt-5">Gemini, the Twins</h1>
                        <p className="legendPara">Gemini is the sign of the Twins. It is the third sign of the zodiac and the first to have a human rather than an animal symbol.</p>
                        <p className="legendPara">The myth of the Twins, like that of the previous sign Taurus, also involves Jupiter and his eye for a pretty face. In this story, the object of his affections is a beautiful woman, Leda, married to Tyndareus, king of Sparta. The lustful god Jupiter, apparently unwilling to try the bull ploy twice (see Taurus), changed himself into the form of a magnificent swan. Details of the encounter are a bit sketchy, but he did manage to seduce Leda while disguised as a swan.</p>
                        <p className="legendPara">From this remarkable union, Leda bore two eggs. The story goes that one of the eggs was the offspring of Jupiter, and that the other was the offspring of Leda's mortal husband. The two eggs produced four children: two brothers, Castor and Pollux, and two sisters, Helen of Troy and Clytemnestra. It is unclear exactly whom Jupiter sired. Some versions of the tale say that Castor and Pollux were his immortal offspring. Others have Castor and Helen as Jupiter's children.</p>
                        <p className="legendPara">In either case, the twin brothers Castor and Pollux grew up strong and stalwart and inseparable. Castor became famous for his skill as a horse-tamer; Pollux was renowned as a superb boxer. When they were young men they joined Jason and his Argonauts on their expedition to find the Golden Fleece. During a storm at sea, two stars appeared over the heads of the twins and the storm miraculously ended. Because of that incident, Castor and Pollux are considered the patron saints of travelers at sea. (During storms at sea, these lights are still seen twinkling at the top of ships' masts and other tall spires. They are caused by the discharge of electricity. The legend is that if two lights are seen, the storm will cease; if only one appears the storm will grow worse.)</p>
                        <p className="legendPara">The twin brothers are described as high-spirited young men. Unfortunately, during a battle Castor met his death. Pollux was inconsolable. At last he went to his father Jupiter to beg him to bring Castor back to life. In turn, Pollux volunteered to give up his own life as ransom.</p>
                        <p className="legendPara">Jupiter rewarded the brothers' great love and attachment to each other by placing them in the sky as stars. There they shine in the constellation Gemini, side by side throughout the ages.</p>
                    </div> : props.sign === "Cancer" ? <div>
                        <h1 className="astroTitle mt-5">Cancer, the Crab</h1>
                        <p className="legendPara">The fourth sign of the zodiac symbolized by the Crab, a water creature that is also capable of walking on land. We know that the crab symbol was placed in the zodiac some five hundred years before Christ. The Chaldeans gave it the name of Cancer, or Crab, because the crab's backward or oblique movement appeared to represent the Sun's movement upon reaching this sign. When the Sun reaches the sign of Cancer (around June 21) it seems to remain stationary for a few days. The Sun's entry into Cancer begins the summer solstice; the very word solstice signifies 'the Sun standing still.'</p>
                        <p className="legendPara">In Egypt, the constellation was called Stars of the Water and was represented by two turtles. (This may have been because the constellation was seen at dawn when the Nile was at its lowest; Nile turtles were rather plentiful at that time of year.) Many astrologers think that Cancer the Crab is a melding of the Egyptian turtles and a Babylonian water creature called Allul, which was apparently a kind of tortoise. All three water creatures - turtles, tortoise, and crab -are similar in important ways. They resemble each other in form, and all are hard-shelled and move slowly (like the Sun's movement on entering Cancer).</p>
                        <p className="legendPara">According to Greek legend, Cancer is the giant crab that attacked the foot of Hercules while he was engaged in battle with the monstrous nine-headed serpent Hydra. Hercules, son of the god Jupiter and a mortal woman Alcmena, had been sent on twelve difficult and heroic undertakings, known as the Twelve Labors of Hercules. One of Hercule's Labors was to slay the evil serpent Hydra. Hercules was having his hands full as the crab attacked, for every time Hercules cut off one of Hydra's heads, two more grew in its place.</p>
                        <p className="legendPara">The crab's attack on Hercules was instigated by Juno, Jupiter's jealous wife, who was set on Hercules's destruction. Unfortunately, the giant crab's attack sealed its own doom, for Hercules crushed it before proceeding to dispatch the Hydra.</p>
                        <p className="legendPara">However, legend has it that Juno was grateful for the crab's attempt to carry out her orders. As a reward for its obedience and sacrifice, she placed the crab's figure in the heavens along with other heroic symbols.</p>
                    </div> : props.sign === "Leo" ? <div>
                        <h1 className="astroTitle mt-5">Leo, the Lion</h1>
                        <p className="legendPara">Leo, the fifth sign of the zodiac, is represented by the Lion, king of beasts. Traditionally, the mythology of the Lion is based on the story of Hercules and the Nemean Lion.</p>
                        <p className="legendPara">Hercules was the son of the great god Jupiter and the mortal woman Alcmena. Jupiter's wife Juno, understandably jealous of Jupiter's numerous love affairs, set herself against Hercules from the time he was a baby. When he was a young man Hercules was compelled to embark on twelve heroic and desperate undertakings known as the Twelve Labors of Hercules.</p>
                        <p className="legendPara">The first Labor was to go to the valley of Nemea and there kill the savage and fearless Nemean lion. The skin of this lion could not be hurt by the weapons of man. Stone, iron, and bronze simply bounced off his pelt. Hercules tried to kill the lion with arrows, but they just fell away from the lion's side. Finally Hercules wrestled with the lion barehanded. Because he possessed such great strength, he managed to get a grip around the lion's neck and strangle him to death. In the process, the lion bit off Hercules's finger, which by any measure would seem to indicate he got off lightly.</p>
                        <p className="legendPara">After he killed the beast, Hercules skinned the magical pelt. From the skin, Hercules made himself a breastplate, and from the lions jaw he formed a helmet. This new armor was to prove very valuable during his subsequent Labors.</p>
                        <p className="legendPara">The constellation Leo is said to commemorate the bravery of combat between Hercules and the magnificent Nemean Lion.</p>
                    </div> : props.sign === "Virgo" ? <div>
                        <h1 className="astroTitle mt-5">Virgo, the Virgin</h1>
                        <p className="legendPara">Virgo is the sixth sign of the zodiac and the second sign to have a human representation rather than an animal one. Virgo is often depicted as a young woman holding a sheaf of wheat, for the constellation of Virgo has always been associated with the harvest. Babylonians called the constellation The Furrow, and it was represented by a corn goddess. The most prominent star in Virgo is named Spica, meaning Ear of Corn.</p>
                        <p className="legendPara">The legend of Virgo is found in the Greek myth of Creation. The story goes that before men or animals lived on Earth, a race of giants, called titans, ruled the world. Two titan brothers, Prometheus and Epimetheus, were given the task of creating human beings and animals. When this was done, Epimetheus set about giving various gifts to the animals - wings to one kind, claws to another, etc. He was so generous that when it came time to dispense something to mankind, he had nothing left to give, so he asked Prometheus for help. Prometheus went into heaven and came back with the gift of fire. This made man superior to other species, for with fire he could keep warm, make tools, and eventually develop commerce and science.</p>
                        <p className="legendPara">Jupiter, chief of gods, became so angry at the gods' secret of fire being given to man that he bound Prometheus to a rock on Mount Caucasus where an eagle constantly tore at his liver, though never entirely consuming it. He also sent a curse to Earth, brought by the first woman. Her name was Pandora, meaning 'a gift of all gods.'</p>
                        <p className="legendPara">Pandora brought with her a box, which she was told never to open. One day, seized with curiosity,  she lifted the lid of the box. Out sprang terrible plagues to haunt mankind forever after: sickness and death for the body; anger, envy, and revenge for the mind. At the bottom of the box lay the one thing that had not escaped - hope.</p>
                        <p className="legendPara">During the terrible times that followed, the gods deserted Earth one by one and went to live in heaven. The very last to leave was Astraea, goddess of innocence and purity. After leaving Earth, Astraea was placed among the stars and became the constellation of Virgo. The legend is that one day the Golden Age will come again, and that Astraea (Virgo) will return to Earth.</p>

                    </div> : props.sign === "Libra" ? <div>
                        <h1 className="astroTitle mt-5">Libra, the Scales</h1>
                        <p className="legendPara">Libra is the seventh astrological sign and the only one to have a symbol that is neither animal nor human. The Scales represent balance and justice, harmony and equilibrium.</p>
                        <p className="legendPara">Like the previous sign, Virgo, Libra is associated with harvest, for in ancient times grains and crops were weighed on scales after they were harvested. The Scales also have a more profound symbolism. They are the scales of judgement for the dead, where souls are weighed.</p>
                        <p className="legendPara">In Egyptian religion the scales of judgement were the sole province of the god Anubis, Conductor of Souls. Anubis, who had the head of a jackal, guided the dead through the underworld and made sure they were weighed fairly. He was the master of balance (the scale). There is in existence a painting, called the Papyrus of Ani, dated around 1500 B.C., that shows a judgement scene. Anubis is crouching by a large scale weighing the heart of a dead person. In one bowl of the scale rests the heart; in the other bowl Truth sits, symbolized by a feather. In this depiction, the scale is equally balanced. In Egyptian religion, the dead heart (or soul) had to be in harmony with Truth before it could pass into the afterlife.</p>
                        <p className="legendPara">The Scales have also been associated with the concept of justice and law. We have all seen statues of the embodiment of Justice. She is a woman who is blindfolded and who holds the scale in her hands. The Scales are the symbol of impartiality, of rendering to each person his or her rightful due.</p>
                        <p className="legendPara">In Greek mythology Justice was represented by the goddess Themis, mother of Astraea (see Virgo). Themis and her daughter Astraea are the constellations of Libra and Virgo, who shine side by side in the firmament. The legend is that when the human race finally reaches its Golden Age, Themis (symbolizing justice) and her daughter (symbolizing innocence) will return to Earth.</p>
                    </div> : props.sign === "Scorpio" ? <div>
                        <h1 className="astroTitle mt-5">Scorpio, the Scorpion</h1>
                        <p className="legendPara">The Eighth sign of the zodiac is represented by the Scorpion, a poisonous creature that can paralyze its victims with the sting of its tail.</p>
                        <p className="legendPara">The sign of Scorpio suffers from its association with the Scorpion, since its symbol is often hated and feared. The Scorpion, however, was not always reviled. In ancient Egypt it was deified in the form of Selket, the Scorpion-goddess. Selket was the protectress of the dead, and she if often seen on walls of tombs with her wings spread out in a protective gesture.</p>
                        <p className="legendPara">The classical myth of the Scorpion begins with the death of Orion, a beautiful young giant and a great hunter who was the son of Neptune (god of the sea). Tales of Orion's prowess, strength, and manliness are legend. The story of his death is related in many versions. One is that Eos, goddess of dawn, fell in love with him and carried him away with her. Diana, the moon-goddess, became jealous that Eos should take a mortal lover and commanded a scorpion to kill Orion.</p>
                        <p className="legendPara">Another version is that Orion tried to rape Diana, and she brought a giant scorpion out of the earth that stung Orion to death.</p>
                        <p className="legendPara">After Orion's death, Jupiter placed both Orion and the scorpion among the stars. They each became a constellation. Orion, with his golden armor and sword in hand, is one of the brightest and most spectacular constellations in the heavens on a winter night. But when the scorpion, who was placed in the zodiac, rises in summer, the brilliance of Orion fades.</p>
                    </div> : props.sign === "Sagittarius" ? <div>
                        <h1 className="astroTitle mt-5">Sagittarius, the Archer</h1>
                        <p className="legendPara">Sagittarius, the ninth sign of the zodiac, is depicted as an Archer, but the Archer is not an ordinary man drawing a bow. He is a centaur, that mythological creature who is half man and half horse. Sagittarius is the only astrological sign to have both a human and animal representation.</p>
                        <p className="legendPara">The constellation of Sagittarius, however, is not just any centaur. It is the great and wise Chiron, a son of the titan-god Saturn. Chiron was a friend and confidant of both gods and men. The gods taught Chiron the arts of medicine, hunting, and riding, music, and prophecy. In turn, Chiron himself became a renowned teacher. Among his famous pupils were Achilles, Jason, Castor and Pollux, and Hercules.</p>
                        <p className="legendPara">One day, while the great Hercules was hunting a dangerous bore, he accidentally struck Chiron in the knee with a poisonous shaft. Chiron suffered the agony of dying, but because he was immortal he could not die. Hercules promised to find Death to release him. On his journey Hercules came across poor Prometheus, chained throughout eternity to a rock where an eagle tore at his liver. The supreme god Jupiter had put a curse on Prometheus: his torture would last until someone of his own free will consented to suffer in his place. The dying Chiron took Prometheus's place. Thus, the curse was fulfilled. Chiron was allowed to die, and Prometheus was set free by Hercules.</p>
                        <p className="legendPara">After Chiron's death Jupiter rewarded his noble character by place the heroic centaur among the stars, and he became the constellation Sagittarius.</p>
                    </div> : props.sign === "Capricorn" ? <div>
                        <h1 className="astroTitle mt-5">Capricorn, the Goat</h1>
                        <p className="legendPara">The tenth sign of the zodiac is represented by the Goat, a sure-footed animal who scales the heights by taking advantage of every foothold.</p>
                        <p className="legendPara">In ancient times, the Goat was depicted as part goat and part fish, with its front half the goat and its back half the fish. In many old drawings and engravings you will see the Goat pictured with a fish tail, and in some astrology books Capricorn is know as the Sea-Goat.</p>
                        <p className="legendPara">The Sea-Goat in the Babylonian religion was a great and revered god name Ea, who brought learning and culture to the people of Mesopotamia. In the valley of Mesopotamia, irrigation of land and crops came primarily from the flooding of the Tigris and Euphrates Rivers. Because of this, people believed there was an ocean of fresh water underneath the earth. The god Ea lived in that ocean. Every day he came out of the underground sea to dispense his wisdom, and every night he returned there.</p>
                        <p className="legendPara">By the time of Greek and Roman culture, Capricorn had become associated with the god Pan, a sporting and lusty creature who ruled over woodlands and fields, flocks and shepherds. Pan was a man from the waist up and a goat from the waist down. He had goat ears and goat horns.</p>
                        <p className="legendPara">Pan was fond of music and was famous for playing the pipes. His shepherd's pipe, called a syrinx, was actually a nymph who had rejected his sexual advances. Pan turned her into a musical instrument, saying that if he could not have her one way she would be his in a new guise.</p>
                        <p className="legendPara">In time, Pan became known as the god of Nature. Certain qualities of Pan's - sexuality, impudence, a love of nature - have become part of the character of Capricorn.</p>
                    </div> : props.sign === "Aquarius" ? <div>
                        <h1 className="astroTitle mt-5">Aquarius, the Water Bearer</h1>
                        <p className="legendPara">The eleventh sign of the zodiac has as its symbol the Water Bearer, a human figure carrying a jar or receptacle from which water pours out in a stream.</p>
                        <p className="legendPara">The symbol of the Water Bearer goes back to both Egyptian and Babylonian religion. In Egypt the Water Bearer was the god Hap, the personification of the river Nile. Hap carried two vases of water, which represented both the South and North Nile, and was considered the sustainer of life. All living things would die without the waters of Hap.</p>
                        <p className="legendPara">In Greek literature the constellation Aquarius was call the Water Pourer, and is sometimes thought to represent the god Jupiter, who at a command caused the waters to pour from heaven. It also commemorates Deucalion, the only man to come through the Great Flood unharmed.</p>
                        <p className="legendPara">At the beginning of creation, gods and humanity lived in harmony during an era called the Golden Age. The earth produced food without people having to till the soil; the waters flowed with wine and honey. Then Pandora opened her box of evils, and plagues and sickness of the mind and body were released on Earth.</p>
                        <p className="legendPara">The great god Jupiter looked down and decided to rid the world of people and create a new race worthier of life. With the help of his brother Neptune, Jupiter covered the earth with water. Only two people saved, Deucalion and his wife Pyrrha, who were both just and pious and who worshipped the gods faithfully. They took refuge on Mount Parnassus, and when Jupiter saw them he remembered their exemplary lives. He caused the waters to recede and the earth to dry up. Then Deucalion and Pyrrha were commanded to cast the bones of their mother behind them. Deucalion interpreted 'the bones of his mother' to mean the stones of earth, and he and Pyrrha began picking up stones and cast them behind themselves as they walked. These stones slowly turned into human beings; the ones Deucalion threw became men, and the stones Pyrrha threw became women. Thus, Deucalion became the father of a new race of mankind.</p>
                    </div> : props.sign === "Pisces" ? <div>
                        <h1 className="astroTitle mt-5">Pisces, the Fishes</h1>
                        <p className="legendPara">The twelfth sign and last sign of the zodiac is represented by two fishes, tied to one another although swimming in opposite directions. The two fishes in the water symbolize conflicting currents of emotion and hidden depths.</p>
                        <p className="legendPara">The constellation of Pisces has been known as Two Fishes as long ago as 2000 B.C. The Babylonian name for this constellation, Kun, has been translated as The Tails (of the fishes). Kun is also known as The Band or The leash (the string that connects the two fishes). Tied to this leash were two fish goddess, Anunitum and Simmah, who represented the Tigris and Euphrates Rivers.</p>
                        <p className="legendPara">In Greek mythology the Two Fishes are associated with a story of Venus and Cupid. A great and terrible monster name Typhon had a hundred dragon heads, eyes that shot fire, and a voice that was a combination of hissing snakes, bellowing bulls, and roaring lions.</p>
                        <p className="legendPara">One day Venus (god of love and beauty) and her son Cupid were walking along the Euphrates River when Typhon suddenly appeared. His hundred heads flicked dark tongues and the eyes flashed fire. Typhon was intent on the goddess's and her son's destruction. Terrified and unable to flee, Venus called on her father Jupiter for help. Jupiter quickly changed Venus and Cupid into two fishes, and they jumped into the river and escaped. Another version of this story is that two brave fishes leapt out of the water to rescue Venus and Cupid and carry them off on their backs through the river to safety. As a reward, Minerva (the virgin goddess) placed the two fishes among the stars, where they became the constellation of Pisces.</p>
                    </div> : ''}
        </>
    )
}

export default AboutAstrologyLegends